# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    paths:
      - .github/workflows/test.yml
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Check formatting
        run: mvn prettier:check --batch-mode --no-transfer-progress

      - name: Tests
        run: |
          mvn clean test --batch-mode --no-transfer-progress \
            -Dgithook.plugin.skip
